print("-------------------------------------------------------")
print("              CALCULADORA SENCILLA")
print("-------------------------------------------------------")

print("1 - SUMA")
print("2 - RESTA")
print("3 - MULTIPLICACIÓN")
print("4 - DIVISIÓN")
print("5 - POTENCIA")
print("6 - DIVISIÓN ENTERA")
print("7 - RESTO DE UNA DIVISIÓN")

opcion=int(input("Ingresar la opción elegida: "))

if opcion==1:
    numero=float(input("Ingresar uno de los sumandos: "))
    numero += float(input("Ingresar el otro de los sumandos: "))
    print("-------------------------------------------------------")
    print("El resultado de la suma es ",numero)
    print("-------------------------------------------------------")
if opcion==2:
    numero=float(input("Ingresar el minuendo: "))
    numero -= float(input("Ingresar el sustraendo: "))
    print("-------------------------------------------------------")
    print("El resultado de la resta es ",numero)
    print("-------------------------------------------------------")
if opcion==3:
    numero=float(input("Ingresar uno de los términos: "))
    numero *= float(input("Ingresar el otro de los términos: "))
    print("-------------------------------------------------------")
    print("El resultado de la multiplicación es ",numero)
    print("-------------------------------------------------------")
if opcion==4:
    numero=float(input("Ingresar el dividendo: "))
    numero /= float(input("Ingresar el divisor: "))
    print("-------------------------------------------------------")
    print("El resultado de la división es ",numero)
    print("-------------------------------------------------------")
if opcion==5:
    numero=float(input("Ingresar la base de la potencia: "))
    numero **= float(input("Ingresar el exponente: "))
    print("-------------------------------------------------------")
    print("El resultado de la potencia es ",numero)
    print("-------------------------------------------------------")
if opcion==6:
    numero=float(input("Ingresar el dividendo: "))
    numero //= float(input("Ingresar el divisor: "))
    print("-------------------------------------------------------")
    print("El resultado de la división entera es ",numero)
    print("-------------------------------------------------------")
if opcion==7:
    numero=float(input("Ingresar el dividendo: "))
    numero %= float(input("Ingresar el divisor: "))
    print("-------------------------------------------------------")
    print("El resultadoresto de la división es ",numero)
    print("-------------------------------------------------------")